### ISSUE TITLE
Path.Combine

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_YearReport#10]
Создание путей тоже через них давай 

![image](https://github.com/user-attachments/assets/5f3c14c4-f79a-4c88-b0b5-d1fc642de548)

**Comment by CTEI1AH** [comment]
<img width="339" alt="{D32D248B-9D81-4AC6-A41C-B7511E08ABB7}" src="https://github.com/user-attachments/assets/50ae3913-c98f-4496-8e0d-2f7437bf1f85">
Ок
