### ISSUE TITLE
Скрипты

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_YearReport#4]
Нет смысла тут в отдельных скриптах. Действий не больше 3. Смысл?
![image](https://github.com/user-attachments/assets/24332d4a-7644-4c27-86dc-7992c1a1cf2a)

![image](https://github.com/user-attachments/assets/d4899492-5003-4024-8bd7-6b77a7fe7722)

**Comment by CTEI1AH** [comment]
Я просто вынес активность сюда, так будет законно?
<img width="195" alt="{3C605C2B-2E69-483E-96E6-36C9A5FE4FB7}" src="https://github.com/user-attachments/assets/b4e29e59-02d7-4aeb-9607-8d3ae5406734">
