### ISSUE TITLE
Скрипт KillAllProcesses

### ISSUE THREAD

**Issue by AAKholod** [CTEI1AH/SBZalesky_Uipath_YearReport#5]
Не делай через консоль закрытие процессов, это фу 
В прошлом проекте акцентировала, если разница в выполнение есть, то отдельно нужно рассмотреть

![image](https://github.com/user-attachments/assets/69c9e008-eef2-4939-948f-ce1ab315d6ea)

**Comment by CTEI1AH** [comment]
Убрал, сейчас оно почему то быстро закрывает
Видимо выключил и включил
